import Head from "next/head";

import { Banner, Footer, Header, Main } from "../components";
import exploreLocationsModel from "../models/exploreLocations";
import cardsDataModel from "../models/cardsData";

export default function Home({ cardsData, exploreLocations }) {
  return (
    <>
      <Head>
        <title>Airnbnb clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Banner />

      <Main cardsData={cardsData} exploreLocations={exploreLocations} />

      <Footer />
    </>
  );
}

Home.propTypes = { ...exploreLocationsModel, ...cardsDataModel };

// prefetch this info on the server before painting the page
export async function getStaticProps() {
  const dev = process.env.NODE_ENV !== "production";
  const apiUrl = dev
    ? "http://localhost:3000"
    : "https://airbnb-clone-kboul.vercel.app/";

  const exploreLocationsResponse = await fetch(
    `${apiUrl}/api/exploreLocations`
  );
  const exploreLocations = await exploreLocationsResponse.json();

  const cardsDataResponse = await fetch(`${apiUrl}/api/cardsData`);
  const cardsData = await cardsDataResponse.json();

  return { props: { exploreLocations, cardsData } };
}
